export const WARNING_CODES = {
  SEO: 'SEO',
} as const

export const INFO_CODES = {
  EXPENSIVE_OPERATION: 'EXPENSIVE_OPERATION',
  TEAM_RESOLUTION: 'TEAM_RESOLUTION',
  ACCESS_DENIED: 'ACCESS_DENIED',
  AUTH_REDIRECT: 'AUTH_REDIRECT',
} as const
